export declare const concat: (...l: any[]) => (a: any) => any;
export declare const filter: (p: any) => (a: any) => any;
export declare const find: (p: any) => (a: any) => any;
export declare const findIndex: (p: any) => (a: any) => any;
export declare const includes: (v: any, s: any) => (a: any) => any;
export declare const join: (s: any) => (a: any) => any;
export declare const map: (c: any) => (a: any) => any;
export declare const reduce: (c: any, i: any) => (a: any) => any;
export declare const reduceRight: (c: any, i: any) => (a: any) => any;
export declare const slice: (...c: any[]) => (a: any) => any;
export declare const sort: (p: any) => (a: any) => any[];
export declare const indexOf: (v: any) => (a: any) => any;
export declare const lastIndexOf: (v: any) => (a: any) => any;
export declare const reverse: (a: any) => any[];
export declare const first: (a: any) => any;
export declare const last: (a: any) => any;
export declare const all: (p: any) => (a: any) => any;
export declare const any: (p: any) => (a: any) => any;
export declare const append: (v: any) => (a: any) => any[];
export declare const prepend: (v: any) => (a: any) => number;
export declare const drop: (c: any) => (a: any) => any;
export declare const dropLast: (c: any) => (a: any) => any;
export declare const take: (c: any) => (a: any) => any;
export declare const takeLast: (c: any) => (a: any) => any;
export declare const flatten: (a: any) => any;
export declare const insert: (i: any) => (v: any) => (a: any) => any[];
export declare const insertAll: (i: any) => (v: any) => (a: any) => any[];
export declare const update: (i: any) => (v: any) => (a: any) => any[];
export declare const updateAll: (i: any) => (v: any) => (a: any) => any[];
export declare const hasMatchIn: (a: any) => (b: any) => any;
